#!/bin/sh
# As an example of using json2tab

if [ "$#" -lt 1 ]; then
    echo "Usage: $(basename "$0") FILE [FILE...]" >&2
    exit 1
fi

tab=$(printf \\t)
result=0
for f do
    if ! pomf_reply="$(curl -sS --progress-bar -F "files[]=@$f" http://pomf.se/upload.php)"; then
        echo "Failed to upload $f" >&2
        result=1
    else
        if ! pomf_id=$(printf %s "$pomf_reply" | ./json2tab | grep -P '^/files/0/url\t' | cut -d"$tab" -f3 | ./junescape) || [ -z "$pomf_id" ]; then
            echo "Failed to parse uploader response to $f" >&2
            printf "Response:\n%s\n" "$pomf_reply" >&2
            result=1
        fi

        if [ "$#" -gt 1 ]; then
            printf "%s: " "$f"
        fi

        echo "http://a.pomf.se/$pomf_id"
        printf '%s\t%s\t%s\n' "$(date --rfc-3339=seconds)" "http://a.pomf.se/$pomf_id" "$f" >> ~/.pomf_history
    fi
done
exit "$result"
